apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-specific-traffic
  namespace: default
spec:
  podSelector:
    matchLabels:
      app: {{ .Release.Name }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    {{- range .Values.networkPolicy.ingress }}
    - from:
        {{- range .from }}
        - podSelector:
            matchLabels:
              app: {{ .podSelector.matchLabels.app }}
        {{- end }}
      ports:
        {{- range .ports }}
        - protocol: {{ .protocol }}
          port: {{ .port }}
        {{- end }}
    {{- end }}
  egress:
    {{- range .Values.networkPolicy.egress }}
    - to:
        {{- range .to }}
        - podSelector:
            matchLabels:
              app: {{ .podSelector.matchLabels.app }}
        {{- end }}
      ports:
        {{- range .ports }}
        - protocol: {{ .protocol }}
          port: {{ .port }}
        {{- end }}
    {{- end }}