apiVersion: v1
kind: SecretProviderClass
metadata:
  name: azure-kvname
spec:
  provider: azure
  secretObjects:
  - secretName: argocd-secrets
    type: Opaque
    data:
    - objectName: ARGOCD_SERVER
      key: ARGOCD_SERVER
    - objectName: ARGOCD_USERNAME
      key: ARGOCD_USERNAME
    - objectName: ARGOCD_PASSWORD
      key: ARGOCD_PASSWORD
    - objectName: KUBECONFIG
      key: KUBECONFIG
  parameters:
    usePodIdentity: "false"
    keyvaultName: "<your-keyvault-name>"
    cloudName: "AzurePublicCloud"
    tenantId: "<your-tenant-id>"
    objects: |
      array:
        - |
          objectName: ARGOCD_SERVER
          objectType: secret
          objectVersion: ""
        - |
          objectName: ARGOCD_USERNAME
          objectType: secret
          objectVersion: ""
        - |
          objectName: ARGOCD_PASSWORD
          objectType: secret
          objectVersion: ""
        - |
          objectName: KUBECONFIG
          objectType: secret
          objectVersion: ""
    resourceGroup: "<your-resource-group>"
    subscriptionId: "<your-subscription-id>"